
name: Unit tests (debug)

on:
  push:
    branches: [ "wjg/ci-cleanup" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install and configure GCC 14
      run: |
        sudo apt install gcc-14 g++-14
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-14
        sudo update-alternatives --set gcc /usr/bin/gcc-14

    - name: Install boost
      uses: MarkusJx/install-boost@v2
      id: install-boost
      with:
        boost_version: 1.73.0
        platform_version: 24.04
        
    - name: Install Catch2 v3 from Source
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout "v3.4.0"
        mkdir build && cd build
        cmake .. -DBUILD_TESTING=Off
        make -j $(nproc)
        sudo make install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose --rerun-failed
